### ISSUE TITLE
Before loading ddskk, M-x skk-edit-private-jisyo does not work

### ISSUE THREAD

**Issue by tkita** [skk-dev/ddskk#100]
場面的にはレアと思われますが、Emacs 起動直後など ddskk が読み込まれる前に M-x skk-edit-private-jisyo を実行するとエラーとなることが判明しました。
手元では修正済ですので、のちほど push します。

**Comment by tats** [comment]
<https://github.com/skk-dev/ddskk/issues/74>での指摘のとおり、

> skk-jisyo-edit-mode.el:211:1:Warning: the function ‘skk-find-coding-system’might not be defined at runtime.
> skk-jisyo-edit-mode.el:211:1:Warning: the following functions are not known to be defined: skk-save-jisyo, skk-reread-private-jisyo

SKK-MK-compileではskk.el, skk-autoloads.elをロードした上で
コンパイルしているので、実行時エラーになりうる警告が無視
されていて、依存関係が大雑把になっているのが現状だと思います。

実行時の`(require 'skk)`や`(require 'skk-macs)`が不足している
ケースがほかにもありそうです。

**Comment by tkita** [comment]
#74 を読み返したところ、 @conao3 さんが正しいですね。私が文脈を読み違えて発言していたようです。大変失礼しました。

**Comment by conao3** [comment]
いえいえ。。
ただ、この作業はとても大変ですね。。

**Comment by tats** [comment]
> SKK-MK-compileではskk.el, skk-autoloads.elをロードした上で
> コンパイルしているので、実行時エラーになりうる警告が無視
> されていて、依存関係が大雑把になっているのが現状だと思います。

SKK-MK-compileについて補足します。skk.el, skk-autoloads.elだけでなく、
skk-server.el, skk-macs.el, skk-vars.elその他コンパイル対象ファイルも順次
ロードされるので、個々のファイルの警告チェックには不向きということになります。

make elcでは個別コンパイルに切り替えていただけたようで、ありがとうございます。
