### ISSUE TITLE
skk-get-current-candidate: Symbol’s function definition is void: skk-henkan-count

### ISSUE THREAD

**Issue by crocket** [skk-dev/ddskk#130]
Version: ddskk-20200301.237

When I type `IKu` in かな mode, I see

```
skk-get-current-candidate: Symbol’s function definition is void: skk-henkan-count
```

in echo area.

**Comment by crocket** [comment]
Somehow, deleting all `.elc` files fixed this issue. Why did it happen?

**Comment by conao3** [comment]
日本語で良いでしょうか。

2,3, 質問をさせてください。

1. Emacsのバージョンは何でしょうか?
2. MELPA版を使われているんでしょうか？
3. emacs -qで起動して、最小init.elを読み込んでも再現しますでしょうか？

とりあえず、こちらの環境では下記のinit.elを `~/.debug.emacs.d/ddskk/init.el` に保存して、 `emacs -q -l ~/.debug.emacs.d/ddskk/init.el` で起動、 `行く` を変換しましたが、正常に変換できるようです。

```emacs-lisp
;; ~/.debug.emacs.d/ddskk/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "prepare leaf"
  (prog1 "package"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize))

  (prog1 "leaf"
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))



(leaf skk
  :ensure ddskk
  :bind (("C-\\" . skk-mode))
  :custom ((default-input-method . "japanese-skk")))
```

**Comment by crocket** [comment]
1. Emacs 26.3
2. use-packageを使ってMELPAからインストールしました。
3. 一度dkskkを削除した後は問題を再現出来ません。

**Comment by tats** [comment]
DDSKKのmasterでは、直近で依存関係について様々な変更がありました。

詳細を確認したわけではありませんが、アップグレード時に過去にイン
ストールしたDDSKKがロードされていて、それがバイトコンパイルに影響
して依存関係が壊れた状態なのではないでしょうか。

もしそうなら、DDSKKの再インストールで解消するはずです。

**Comment by crocket** [comment]
多分アップグレーど時の問題だと思います。

**Comment by tats** [comment]
skk-henkan-count関数は最新のmasterでは存在しませんが、存在している
ころのファイルがバイトコンパイル時に使われたものと思います。

**Comment by crocket** [comment]
ddskk-16.2からアップグレードしました。
