### ISSUE TITLE
MELPAでddskkではなくskkとして配布する

### ISSUE THREAD

**Issue by conao3** [skk-dev/ddskk#165]
「travis とか melpa とか workflows とか(#90)」で立候補した通り、MELPAについては私が管理したいのですが、ddskkがMELPAでskkではなく、ddskkと配布されている経緯が少し分かりません。

プレフィックスについて、Elispにおいては名前空間が分離されていないので利用については慎重になる必要があります。
基本的には「パッケージ名.el」が含まれ、ファイル分割する場合には「パッケージ名-*.el」と命名し、その内部のシンボルもそれぞれのプレフィックスを使用することが慣習です。

ddskkではなく、skkというプレフィックスをファイル名とシンボルに使っているのでMELPAにもskkという名前で登録するのが自然だと思っています。

この件についてご意見を募集したいのですがいかがでしょうか。

考えられるメリットとデメリットは以下です。

### メリット
- 一貫性の向上。
- [leaf.el](https://github.com/conao3/leaf.el)や[use-package](https://github.com/jwiegley/use-package)による設定の記述の削減 (これは一貫性の向上による自然な効果です)

### デメリット
- MELPAでインストールしているユーザーのinit.elの変更。
```
(package-install 'ddskk) -> (package-install 'skk)
```

---

経緯について少し調べると https://github.com/melpa/melpa/pull/2214 でskkとしてMELPAに導入され、 https://github.com/melpa/melpa/pull/2303 でddskkにリネームされたようです。
これらのコミットは @myuhe さんが中心で動かれているようなので、ぜひ @myuhe さんにもご意見を頂ければと思います。

**Comment by tkita** [comment]
`SKK' の成果物を引き継ぐ形で新たな開発が始まった際に、`SKK' と区別するために `Daredevil SKK' と命名されたようです。
そのときに、ファイル名やシンボル名は skk のまま引き継いで現在に至っているのだと思われます。ファイル名やシンボル名が ddskk へと変更されなかった理由は分かりません。
以上は、私もドキュメント上でしか知り得ないことなので、事実と異なっていたらすみません。

なお、MELPA 上での登録名称を変更することについて、私自身は特にこだわりありませんので実施していただいても結構です。実施の際にはドキュメントの修正もお願いします。

**Comment by tats** [comment]
> ddskkではなく、skkというプレフィックスをファイル名とシンボルに使っているのでMELPAにもskkという名前で登録するのが自然だと思っています。

Daredevil SKK (DDSKK)という名称は、まだ開発が続いていたフォーク元のオリジナルと区別するために付けられたもののようで、その機能としては、おっしゃる通りskkという名前を使うのが自然だと思います。

ちなみにDebianパッケージでは、skkとddskkの両方が存在した過去の経緯からパッケージ名ddskkをそのまま使っていますが、skk機能を提供するddskkパッケージとして、インストール時にはskkという名前も指定できるようなっています。

> 経緯について少し調べると melpa/melpa#2214 でskkとしてMELPAに導入され、 melpa/melpa#2303 でddskkにリネームされたようです。

melpa/recipes/ddskkでは`:old-names (skk)`としてあって両方の名前が使えることを意図しているのかと思いましたが、package.elレベルではold-namesのサポートはなくてddskkの名前しか使えない状況なのですね。

現時点でさらにリネームする必要性については微妙な気がしますが、個人的にはどちらでもとくに異論はありません。

**Comment by conao3** [comment]
ありがとうございます。1週間程度さらに意見を募集して、考えたいと思います。

**Comment by tkita** [comment]
この辺かな。議論の内容は覚えていません。
https://web.archive.org/web/20150922030501/http://mail.ring.gr.jp/skk/201501/threads.html

HOME ディレクトリを消失させてしまう事故があり、あいにく手元にはメール残っておりません。

**Comment by elim** [comment]
たまたま tkita さんが示されたあたりのメールを保持していたため参照してみましたが、リネームの経緯は見当りませんでした。

具体的には:

2014-11-24 投稿の `[skk 7795] MELPAのDDSKKレシピ登録` から
2014-12-23 投稿の `[skk 7892] ddskkのpackage` あたりまでを読みました。

2014-12-21 に [melpa#2303 Rename skk to ddskk](https://github.com/melpa/melpa/pull/2303) が出されており
2014-12-22 にそれが merge されてますので

メーリングリストではパッケージ改名については話し合いがなかったのかもしれないと思いました（もしメールの読み落としがあったら申し訳ないです）

**Comment by conao3** [comment]
お騒がせしましたが、Emacs-jpでの意見交換もあり、再度メリットとデメリットを比較した結果、ユーザーに与える混乱の方が大きいように感じました。
ひとまずこちらの提案についてはcloseさせて頂きたいと思います。

---

参照用にEmacs-jpのログを貼りますが、発言当時は私も含め、スレッドに参加されたみなさんもGitHubに公開されることを想定していなかったことをご留意頂けると幸いです。
<details>
<summary>Emacs-jpでの意見交換</summary>

conao3 今日 20:07
MELPAのddskkをskkにリネームするissueをddskkに立てました。
なにかご意見ありましたらお願いします。
https://github.com/skk-dev/ddskk/issues/165

elim  19時間前
その issue で示された当時のメーリングリストのメール、わたしのてもとにありそうです

conao3  19時間前
お、すごい

elim  19時間前
ただ、改名に関するメールはまだ見当らず……
MELPA 登録のやりとりは観測できました
https://github.com/milkypostman/melpa/pull/2116 の相談など

elim  19時間前
うまいことなんとか渡したい

elim  19時間前
（無意味かもしれないけど

conao3  19時間前
elimさんが手元で見て情報がないのなら私が見ても情報を取れないかも。。？
とりあえず過去の調査より今のddskkのユーザーのことを考えるのが重要と思うようになりました。

elim  18時間前
とりあえず、調べたことなどを issue にも投稿しておきました。
実際のメールの内容などどこまで書いてよいかわからず（権利的にも、分量的にも）、ほぼ書いておりませんのでまったく証拠能力がありませんが :see_no_evil: 

conao3  18時間前
いえいえ、ありがとうございます!

elim  18時間前
個人的には https://github.com/melpa/melpa/pull/2303#issuecomment-67765936 これはこれで妥当なお考えだと思いましたので
ddskk のままでもよいのでは、と思いました

conao3  18時間前
そもそもskkにすればpkgファイルを削除できるんですよね

conao3  18時間前
cccとcdbとかも分けてあるけど誰も使ってないのでddskkの内部に回収したい

elim  18時間前
なるほどそういう事情もあるのですね

elim  18時間前
佐藤先生に「 DDSKK が今の SKK ですね」みたいなことを言っていただけたら八方丸くおさまりそう（冗談半分です

conao3  18時間前
そもそもddskkになったのならプレフィックスを全部ddskkに変えるべきだったのでは。
helmはそうやってフォークしましたし 

chuntaro  6時間前
歴史的なソースコードなので、配布サイトの都合で変更する事には少し抵抗が…
prefixは他と区別出来れば何でも良いはずなので、skkのままで良いはずだけど、登録するときには
skkにすべきだったんだなと。
ただ、今更変更する事が出来るのだろうか…

conao3  6時間前
ソースコードの変更は難しそうです。
さらにforkして変えるのはできるかもしれませんが、ddskkのプロジェクトはもう変えられない。。
Melpaのold-nameを設定しても普通に404になるのも問題を難しくしてますよね。。

chuntaro  5時間前
不勉強でold-namesなるものを知らなかったけど、調べたら今は動いてないと…残念
MELPA自体のソースコードを見たこともないので、簡単に直せるものなのかも全然分からない…

conao3  5時間前
(package-install 'ddskk) をした後に (require 'ddskk) してエラーになるのはやはりおかしいと思うんですよね。。
old-namesでリダイレクトしたらどうなるのか(package.elが扱えるのか)ちょっと調査してみます。

conao3  2時間前
リダイレクトを試してみましたが、Melpaの色んなファイルを整合性を持って編集しないといけないので大変でした。
普通にddskkとskkの2つのレシピを登録しておくとddskkでもskkでもインストールできるので、これだと動作を壊さない。。？(マージされるかどうか分からない)

chuntaro  42分前
パッケージ名はもうしょうがないと諦めるしか…
ちなみに、skk使う時は
(setq default-input-method "japanese-skk")
だけで良いので、直接requireする人はあまりいないような気もします。

conao3  19分前
まぁ実際リネームしたらddskkをインストールしようと思ってskkをインストールしなければならないってことになるんですよね。。
あまりメリットがない。。ですかね。

conao3  18分前
ちょっとcloseしてきます :dash:

chuntaro  4分前
今回は直接reuqireする使い方をしないだけで、基本的にはパッケージ名とrequireする名前は一致してる方が良いという感じですかね。

conao3  1分前
そうですね。一般的にはそうだと思います。やはり歴史があるものは難しい。。
このスレッドを参照用にGitHubに貼りたいのですが大丈夫でしょうか @elim @chuntaro

chuntaro  < 1分前
もちろん全然問題ないです！

elim  < 1分前
問題ないですー

conao3  < 1分前
ありがとうございますー!
</details>

**Comment by elim** [comment]
> この辺かな。議論の内容は覚えていません。
> https://web.archive.org/web/20150922030501/http://mail.ring.gr.jp/skk/201501/threads.html
> 
> HOME ディレクトリを消失させてしまう事故があり、あいにく手元にはメール残っておりません。

やや off-topic かもしれないですが、こちら今も netnews としては参照できるそうです。

<news://news.ring.or.jp/>

私も手元の news client (Thunderbird 78.1.0) で読めることを確認できました。

（こちらも Emacs-jp Slack で教えていただきました）
