### ISSUE TITLE
skk-azikの「tU」->「っ」定義について

### ISSUE THREAD

**Issue by conao3** [skk-dev/ddskk#184]
ref: https://www.grugrut.net/posts/201910222100/
現在、「tU」が「っ」(小さい「つ」)として定義されており、これは先のブログで指摘されているように多くの誤爆が発生します。
https://github.com/skk-dev/ddskk/blob/a66a7b16f13533afdd03e21eebcdd6309e469a13/skk-azik.el#L406

azikの本家はこの [Vectorのページ](http://hp.vector.co.jp/authors/VA002116/azik/azikinfo.htm) かと思いますが、このエントリについては記載がありません。
skk-azik独自の拡張であれば、これは個人用のテーブルに移してもらって、skkが提供するazikとしては外したいのですが、経緯についてご存知の方はおられますでしょうか。。？

**Comment by conao3** [comment]
blameしてみたところ18年前のコミットのようです。
個人的には大文字を含んでローマ字定義があるのは違和感があるのですが、いかがでしょうか。。？
https://github.com/skk-dev/ddskk/commit/296d21441027f12dac22e9d479972c712a61fc27#diff-29def1c9cf073c78058fb41ddced82b8530494bd2ee24bb1ca7e25e9413d7197R485

**Comment by tkita** [comment]
あいにく経緯は知り得ていませんが、直しちゃっても良いと思います。
感覚的でスミマセン。
