### ISSUE TITLE
.travis.yml について

### ISSUE THREAD

**Issue by tkita** [skk-dev/ddskk#21]
`.travis.yml` に、自身の役割・機能についてのコメント書きを追加してください。
あとの方が保守できるよう（GNU Emacs 25 のリリース又はGNU Emacs 22 のサポート廃止の際に当該ファイルを保守できるよう）、適度なコメントも追加してください。

**Comment by yutopia** [comment]
#38 にも書いたことですが、XEmacs でのテストにも使えるといいかと。
