### ISSUE TITLE
emacs-29とddskk masterでisearchを使えば「Lisp error: (void-function nil)」が出ます

### ISSUE THREAD

**Issue by elizagamedev** [skk-dev/ddskk#210]
すみません。日本語がよくできないんです。特にパソコンを使える言葉はほとんど分かりません。

ですけど、タイトルのとおりなんです。`emacs -Q`をして、それから、

```
(add-to-list 'load-path "~/ddskk")
(require 'skk-autoloads)
(require 'skk)
(setq skk-isearch-mode-enable 'always
      skk-isearch-start-mode 'hiragana
      default-input-method "japanese-skk"
      debug-on-error t)
```

をして、`isearch-forward`をして、「な」とかを書いてみたら、このbacktraceが出ます。

```
Debugger entered--Lisp error: (void-function nil)
  nil(97)
  isearch-with-input-method()
  funcall-interactively(isearch-with-input-method)
  command-execute(isearch-with-input-method)
  isearch-process-search-multibyte-characters(97 1)
  isearch-printing-char(97 1)
  funcall-interactively(isearch-printing-char 97 1)
  command-execute(isearch-printing-char)
```

その`void-function`は`input-method-function`らしいです。

emacs-29はまだ途中だからこのerrorを直せない場合なら、すみません。

**Comment by tats** [comment]
`(require 'skk-setup)` may prevent the issue.

skk-autoloads and skk-setup are required by leim-list.el,
otherwise by hand.

**Comment by tats** [comment]
Ah, it seems skk-setup.el and leim-list.el are not installed with MELPA.

See "Isearch setting" in the source file skk-setup.el.in to setup by hand.

  - https://github.com/skk-dev/ddskk/blob/master/skk-setup.el.in

**Comment by tkita** [comment]
Please also refer to the following documents:

.../READMEs/INSTALL.MELPA.md

**Comment by elizagamedev** [comment]
Thank you, copying the relevant parts from skk-setup.el into my init.el has resolved the problem. The English readme only mentions setup.el as defining keybindings, but I see now that the Japanese version is very specific about using it for `isearch`. I will create a PR to update the English text.

However, compared to other Emacs packages, this seems unusual. Perhaps instead there should be a global minor mode `skk-isearch-mode` which performs the same task of advising functions? If I have time I might try to implement this.

**Comment by tkita** [comment]
関数 skk-version の値で make 版と melpa 版の区別ができるので、ddskk 起動時に melpa 版に向け「isearch 設定してね」等を促す表示は可能ですね。
時間あるときに実装しておきます。

**Comment by elizagamedev** [comment]
今の状態より、そんなメッセージが示さばいいと思いますね。まだ先の想像のskk-isearch-modeのほうがやりたいけど、今の日本語の程度が足りないかもしれません
