### ISSUE TITLE
build error ?

### ISSUE THREAD

**Issue by yutopia** [skk-dev/ddskk#28]
https://github.com/skk-dev/ddskk の下のところに表示されている README.md なんですが、そこに build error とあるのですが、これは私の環境だけなんでしょうか？
クリックすると Travis CI のサイトに飛んで、そこの My Repositories のところで #89 errored が表示されています。

master - fix docstring で error が起きたみたいですが。

Travis CI の Log を見ると、#89.1 EMACS=emacs22 と #89.2 EMACS=emacs23 で error となっているようで、#89.3 EMACS=emacs24 では pass してるとあります。

念のため master を clone してきて emacs-24.4 の元で make test しましたが、これは pass しています。
手元の環境で emacs-22.3 と emacs-23.4 で make test すると、確かに failed となりました。

**Comment by tkita** [comment]
昨夜、savannah.gnu.org や lists.gnu.org に繋がらない時間帯がありました。　@yutopia さんが試したときには gnu.org が復旧していたのだと想像します。
なので、 Travis CI も make test を再チャレンジしてくれれば pass すると思われますが。
.travis.yml や make test をcommit した方は、 #21 #22 #23 を実施してください。

**Comment by tkita** [comment]
さきほど、ひとつ commit したら、即座に Travis CI が pass しました。
Travis CI が commit を監視しているのか、github 側に通知機構があるのか、、、

**Comment by yutopia** [comment]
make EMACS=/MY/EMACSDIR/bin/emacs.exe  downloads elc test
で local でもテスト が pass することを確認しました。
Travic CI が pass してるのも気付きました。
commit したときに .travis.yml が実行されるということでしょうか。
