### ISSUE TITLE
MELPA のブランチ 関係図について

### ISSUE THREAD

**Issue by yutopia** [skk-dev/ddskk#29]
#19  に上げた MELPA の関係図ですが、もしかしてこれは close したあとにコメントしていたので見えなくなっていたでしょうか。

事実誤認などありましたら指摘願います。
必要でしたら、元の svg もどっかに上げておきましょうか？
もう用済みでしたらすみません。

**Comment by tkita** [comment]
私は MELPA に対して commit したことないので、図の正誤は判断できません。
今後、ddskk 配布物のディレクトリ名／ファイル名に変更が生じた場合は、同時に MELPA の recipe も保守する必要があり、その時に（その担当者に） #19 の図が活用されることでしょう。

**Comment by yutopia** [comment]
今後どこにこの図を置いておくかはともかく、とりあえず備忘録として open にしておきます。

**Comment by yutopia** [comment]
今回 MELPA の recipe を書くにあたって行った手順をまとめておきます。

1. MELPA を fork
2. fork したMELPAを local に clone
3. 必要に応じて改編用に branch を切る
4. recipe の修正 ( recipe/ddskk )
5. テスト
   *  make reicipe/ddskk を実行  (mingw/cygwinなどで Emacs にパスが通ってないときは make EMACS_COMMAND=/c/usr/emacs/bin/emacs.exe recipe/ddskk のようにして emacs のパスを指定)
   * 正常に動作していれば package/ddskk-......tar にインストールされる一式が作られるので、中見の確認
6. git add -u && git commit
7. origin に push
8. pull request 作成

本当は flycheck.el での check をするようにということです。 https://github.com/purcell/flycheck-package
