### ISSUE TITLE
ccc.elの単独パッケージ化

### ISSUE THREAD

**Issue by myuhe** [skk-dev/ddskk#3]
カーソルのカラーを変えるライブラリccc.elですが、単独のパッケージとしてMELPAに登録することを提案します。

ccc.el は単独のパッケージとしても非常に有用なライブラリではないかと思っています。

cf. http://d.hatena.ne.jp/kitokitoki/20110815

方針としては、リポジトリのディレクトリ構造は変えず、MELPAのrecipe上で分離させようかと思っています。

**Comment by kenoss** [comment]
気付いたことをいくつか書きます. さらっと見ただけですのでよしなに.

- MELPA に登録するなら名前空間をちゃんと使った方が良いと思います.
- 説明が(ほとんど)ないのでぱっと見何をするパッケージなのかわかりにくいかと.
- post-command-hook は代替でどうにかできると思います.
  evil も同様の処理をしていましたが, `window-configuration-change-hook` と `select-window` へのアドバイスで行けると思います. (まだパッチが取り込まれていないので漏れがあるかもしれません. 意見歓迎.)
  https://bitbucket.org/lyro/evil/issue/441/not-good-use-of-post-command-hook-for-evil
  https://bitbucket.org/lyro/evil/pull-request/3/stop-using-post-command-hook-to-refresh
  いかがでしょうか?

**Comment by myuhe** [comment]
#30 で名前空間の整理、コメントヘッダーの修正を行ないました。

@kenoss 
コメントありがとうございます!! 参考にさせていただきました。
`post-command-hook` の件、確かにその方が良いので、いろいろ試したのですが、`make-frame-command`などでフレームを作る際にどうしてもエラーが出てしまい、詰んでしまいました。
良ければ、pull req もらえると助かります!!

**Comment by masatake** [comment]
GNU Emacs 26.1 の select-window の説明をみていて発見したのですが、buffer-list-update-hook というのがあります。昔はなかったように思います。 select-window への adviseにかわにこれが使えないかと思っています。
