### ISSUE TITLE
Emacs 25.0.50 での compile 時 warning 

### ISSUE THREAD

**Issue by yutopia** [skk-dev/ddskk#34]
#33  のテストのために Emacs25.0.50 2015-02-17 で ddskk を bytecompileしてみたのですが、以下のwarningが出るようです。
````
$ make EMACS=/cygdrive/c/usr/emacs-25.0.50/bin/emacs.exe elc
/cygdrive/c/usr/emacs-25.0.50/bin/emacs.exe -batch -q -no-site-file -l SKK-MK -f SKK-MK-compile
Loading c:/cygwin64/home/yutopia/skk/ddskk/SKK-CFG...
Loading c:/cygwin64/home/yutopia/skk/ddskk/skk-autoloads.el (source)...

In end of data:
skk-comp.el:608:1:Warning: the function `smart-find-file-all' might not be
    defined at runtime.
````
Emacs は http://sourceforge.net/projects/emacsbinw64/files/snapshot/ から取ってきたものです。
HEAD でも試してみましたが同様となります。

Emacs が起動してる状態だとserverが動くのかwarningは出ません。
ちなみに、compile過程が表示されないのですが、compileは通っているみたいです。

**Comment by yutopia** [comment]
ちなみに、25 だけでなく 24  でもそうでしたが、package でインストールするときは warning がでまくります。
これは autoload の関連なんでしょうか？

**Comment by tkita** [comment]
smart-find-file-all に関する warning は b928b3 で対処済みです。
