### ISSUE TITLE
メーリングリストに参加できません。

### ISSUE THREAD

**Issue by teika-kazura** [skk-dev/ddskk#37]
(2015-08-02) まとめ: もしskkのメーリングリストに参加しようと skk-subscribe@ring.gr.jp に送信したものの、送信側のサーバーから、「送信できない」旨のメッセージが届いたならば、ring側のサーバーから、あなたのメールサーバー(のドメイン)がスパムフィルターで拒否されている可能性があります。フリーメール以外も試して下さい。どうしても無理ならば、このissueで相談すれば、ring側でフィルターを修正して下さる可能性もあります。

---

(7/4 加筆) skk のメーリングリストに参加できません。skk-subscribe@ring.gr.jp にメールを送りましたが、送信元のメールサーバーから、「送信できません」と言われます。

6/16-20, 21-25、7/2, 7/4の期間に送れませんでした。直接 skk@ring.gr.jp にも送ってみましたが、同じ事でした。

6/19頃には、MLへの投稿がありましたので、ダウンしている訳ではなく、送信元がスパム扱いでもされているのでしょうか? 送信に使ったのは、gmx.com 及び aol.com です。昨年の12月にも、似たような方がいて、「リジェクトされた」そうですが、正確な事は分かりません。(myuheさん宛てに、ツイッターで投稿されていました: https://twitter.com/yasushia/status/541026531242291200 )

www.ring.gr.jp はブラウズできますし、MLのアーカイブも見られます。なお御存知かも知れませんが、2012年の8月頃には、MLは生きていた一方、http://openlab.jp/skk が何日かダウンしていました。

エラーメッセージは、以下の通りです:

---

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. The following address
failed:

skk-subscribe@ring.gr.jp

Reason:
delivery retry timeout exceeded

---

こちらに書くのがベストかどうか分かりませんが...北本さんもご多忙のようですし...

実現性はさておき、べき論だけを書くと、ring サーバー群やopenlabの中で、いまだに活動中なのはskkぐらいのようならば、他のホストに移動すべきなのかも知れません。また、MLはgmaneやmail-archive.comでは保存されていないので、アーカイブも保全する事が望ましい、とも言えます。

**Comment by tkita** [comment]
いちおう言い訳しておきます。
私は、cvs への commit 権を与えられただけであり、 ring.gr.jp の運営に携わってはおりません。

**Comment by yutopia** [comment]
言い訳だななんて、そんなことはないと思います。
立場を明確になされることは大事ですし。
誰がどこまでできるのかわかりにくくなっていますし。
作業できる人ができるところからやっていくしかないですよね。

**Comment by tats** [comment]
> スパム扱いでもされているのでしょうか? 送信に使ったのは、gmx.com 及び aol.com です。

手元では、SKK Openlabのメーリングリストに限らず、ocn.ne.jpでは送信できないことが
いくつかあり、gmail.comのSMTPサーバーを使うようになりました。

> 他のホストに移動すべきなのかも知れません。

GitHubへの一部リソースの移行を進めていて、その他必要に応じて検討、
という状況かと思います。

メーリングリストについては、当面はGitHubのissueで十分なのかもしれません。

**Comment by teika-kazura** [comment]
Yahoo$B%a!<%k$G$bBLL\$G!"%(%i!<%3!<%I(B 4.4.2 $B$G$7$?!#(Baol$B$G$O(B 5.4.2 $B$G$7$?!#A0<T$O<u?.B&(B (ring) $B$N%5!<%P!<$,Aw?.85$r%9%Q%`07$$$N2DG=@-!"$H$N>pJs$b$"$j$^$9$,!"$=$b$=$b%(%i!<$,(B2$B<oN`$"$j$^$9$7!"$I$&$J$s$G$7$g$&!#$J$*(Bsmtp$B$N%(%i!<%3!<%I$GA0<T$O(B "The connection was dropped during connection", $B8e<T$O(B"Bad connection"$B$H$N;v!#(B

$B30It$G$N%"!<%+%$%V2=$K4X$7$F(B: gmane.org$B$G(Bskk$B$N(BML$B$r%"!<%+%$%V$9$k$h$&!"%j%/%(%9%H$r$7$?$i!"!V<u$1IU$1$?!#:G=i$NEj9F$,M-$C$?;~E@$G%K%e!<%9%0%k!<%W(B gmane.emacs.skk $B$,:n$i$l$k!WM3!"DLCN$,Mh$^$7$?!#(B(ML$B;22C$,$G$-$?!"$H$$$&$3$H$G$7$g$&$+(B??) $B$J$*!"(Bmail-archive.com $B$G$b%"%/%;%92DG=$K$J$k$O$:$G$9!#(B
$B$^$?2a5n$NEj9FJ,$b!"%G!<%?$rDs6!$9$l$P!"J]B8$7$F$b$i$($^$9!#MWNN$O$3$A$i$G$9(B: http://gmane.org/import.php $B%U%!%$%kKh$K(B1$BEj9F(B($B$r(B1$B%G%#%l%/%H%j$K(B?)$B<}$a$?(Btarball$B$+!"(BUnix$B$N(Bmbox$B7A<0$N$_2DG=!"$H$N;v$G$9!#(B

$BKLK\$5$s[)$/(B:
> $B$$$A$*$&8@$$Lu$7$F$*$-$^$9!#(B
> $B;d$O!"(Bcvs $B$X$N(B commit $B8"$rM?$($i$l$?$@$1$G$"$j!"(B ring.gr.jp $B$N1?1D$K7H$o$C$F$O$*$j$^$;$s!#(B

$BIt30<T(B($B$7$+$bF?L>$N(B)$B$,>!<j$K8F$SN)$F$F<:Ni$7$^$7$?!#(BOhmura$B$5$s$N%3%a%s%H$+$i$9$k$H!"3+H/<T!&4IM}<T4V$G$N$3$NN`$N>pJs$N6&M-$K!"2~A1$NM>CO$,$"$k$h$&$K$bFI$a$^$7$?!#(B

$BDj2H(B ($B$F$$$+(B)

**Comment by elim** [comment]
iso-2022-jp でのメール投稿は化けるようです…… :sweat_smile:

ということで余計かもしれませんが…… :arrow_down_small:

> Yahooメールでも駄目で、エラーコード 4.4.2 でした。aolでは 5.4.2 でした。前者は受信側 (ring) のサーバーが送信元をスパム扱いの可能性、との情報もありますが、そもそもエラーが2種類ありますし、どうなんでしょう。なおsmtpのエラーコードで前者は "The connection was dropped during connection", 後者は"Bad connection"との事。
> 
> 外部でのアーカイブ化に関して: gmane.orgでskkのMLをアーカイブするよう、リクエストをしたら、「受け付けた。最初の投稿が有った時点でニュースグループ gmane.emacs.skk が作られる」由、通知が来ました。(ML参加ができた、ということでしょうか??) なお、mail-archive.com でもアクセス可能になるはずです。
> また過去の投稿分も、データを提供すれば、保存してもらえます。要領はこちらです: http://gmane.org/import.php ファイル毎に1投稿(を1ディレクトリに?)収めたtarballか、Unixのmbox形式のみ可能、との事です。
> 
> 北本さん曰く:
>> いちおう言い訳しておきます。
>> 私は、cvs への commit 権を与えられただけであり、 ring.gr.jp の運営に携わってはおりません。
> 
> 部外者(しかも匿名の)が勝手に呼び立てて失礼しました。Ohmuraさんのコメントからすると、開発者・管理者間でのこの類の情報の共有に、改善の余地があるようにも読めました。
> 
> 定家 (ていか)
> 
>

**Comment by tkita** [comment]
大村さんがおっしゃった「誰がどこまでできるのかわかりにくくなっている」は、私もそのとおりだと思ってます。特にサーバサイドで実行されているスクリプトなど。
そこで、定家さんがおっしゃった「他のホストに移動すべきなのかも知れません」は、状況を心機一転するよい手段かもしれませんね。移転しましたと宣言するだけです。

移転するとなると、辞書は DDSKK(elisp) 以外も参照に来ているので影響がありそうですね。

**Comment by yutopia** [comment]
今、状況を確認するためにSKK Openlabトップに行ってみたのですが、いつのまにかWikiが復活しているようです。
まさかとは思いますが、MLの方も復帰してるということはないですよね？
エラーの内容からそれは無いかと思いますが。
ちなみに、Wikiの方のパーミッションは変わっていないようですが、アクセスした時点でlogｈディレクトリは更新されていたようです。(アクセスは不可)

どうしましょう。議論は skk-dev/temp_web に移行した方がよいでしょうか？

**Comment by tkita** [comment]
ML の subscribe についてです。ring の方に問い合わせてみたところ、『spam 対策のため、かなり以前から aol.com および gmx.com はドメインごとはねていた』そうです。とりあえず、はねるドメインから外していただいたようです。

**Comment by tkita** [comment]
http://dir.gmane.org/gmane.emacs.skk
定家さん、ありがとうございます。

**Comment by teika-kazura** [comment]
> http://dir.gmane.org/gmane.emacs.skk
> 定家さん、ありがとうございます。

少し勇み足だったかもしれません。skkのメーリングリストは、かつては、他のホストではアーカイブして欲しくない、という方針だったようです。手元の過去のメッセージを見ると、ヘッダに
`X-No-Archive: yes`
という行がありますので。(参考: https://en.wikipedia.org/wiki/X-No-Archive ) おそらく、現在ではgmaneでのアーカイブ化に反対の方はいらっしゃらないのではと思いますが、いずれにせよ、gmaneではこれを尊重して、14日間のみ保存し、その後は消されてしまいます。この方針に関しては、ML管理者の要請により、無視させることもできる、との事です。参照: http://gmane.org/expiry.php

それからもう一点、現時点では、返信に含まれるメアドが丸見えになっています。これはスパム防止の為にはあまり良くないですが、これは
`X-Archive: encrypt`
という行を入れると、gmane側ではボット収集を防ぎつつ、人間には読める形で公開、としてくれます。[こんな感じ](http://gmane.org/get-address.php?address=jmyeez-Re5JQEeQqe8AvxtiuMwx3w%40public.gmane.org)です。(Captchaみたいなやつです)
送信者のアドレスは、無条件にこの形になっています。(そもそも、メーリングリストの登録したアドレスは収集される前提の物を使うべきなのは、言うまでもありませんが。)

スパムフィルターの件ですが、gmx.comでもaol.comでもまだ送れませんが、ringさん側が、未対応なのかも知れませんので、しばらく様子を見ます。ただ、一々skkの管理者さんにお願いして、ringに頼む、というのもどうなのか。実際、フリーメールはスパムの源になっているからこそ、フィルターされているのでしょうし...とりあえず、本issueの[最初の書き込み](https://github.com/skk-dev/ddskk/issues/37#issue-89884722)に、スパムとしてハネられている、という事だけ書いておきました。
