### ISSUE TITLE
skk-get

### ISSUE THREAD

**Issue by tkita** [skk-dev/ddskk#40]
新たなコマンド skk-get を追加してみました。
M-x skk-get と実行すれば、辞書ファイルをダウンロードします。保存先は skk-get-jisyo-direcroty であり、標準は ~/.emacs.d/skk-get-jisyo です。

「elpa によるインストール時」又は「インストール直後の初回起動時」に skk-get を実行するようにすれば便利かもしれません。

**Comment by tkita** [comment]
o Makefile に get を追加しました。make get で ./dic にダウンロードします。
o 対話的インストーラも対応。質問に答えると、./dic にダウンロードします。

**Comment by yutopia** [comment]
MELPA のrecipe で package install されるときに自動的に反映されると便利ですが、どうにもやり方がわからないです。
https://github.com/milkypostman/melpa/blob/master/README.md

 https://github.com/skk-dev/ddskk/blob/master/READMEs/INSTALL.MELPA.md に記述を書き加えましょうか？

**Comment by yutopia** [comment]
@tkita  #22 関連で、skk-get のテストって書けますか？
過去のを列挙していくのは面倒ですが、機能が追加されたときにテストコードを書いてしまえばあとで楽かなぁ、と。
skk-get を評価して辞書がダウンロードされてることを確認できればいいんでしょうかねぇ？

**Comment by yutopia** [comment]
Windows 環境の Emacs 24.4 と http://sourceforge.net/p/emacsbinw64/wiki/Build%20guideline%20for%20MSYS2-MinGW-w64%20system/ で取ってきた最新版の両方だけでテストしたのですが、gzip もしくは tar で取得に失敗します。
Windows 環境だと gzip コマンドと tar コマンドが無いためです。 
MinGW-w64 でコンパイルしたものは、サイトの指示の通りに *.dll ファイルをコピーする際に libbz2-1.dll がコピーされているためか gzip 解凍は完了してるみたいです。

**Comment by tkita** [comment]
Windows 環境は何か対策考えてみます。

**Comment by tkita** [comment]
gzip コマンドが無い場合、*.gz を powershell スクリプトで解凍するようにしてみました。
引き続き *.tar も考えます。

**Comment by yutopia** [comment]
以前、jka-compr.el を使っているのをみかけたことがあるんですが、外部コマンドを前提としてるみたいですね。

native だと tar-mode とかがあるみたいですけど、ロードされっぱなしというのも SKK 的でないような気もします。

**Comment by yutopia** [comment]
Emacs 22.3, Emacs 23.4, Emacs 24.4 で動作確認しました。
23.4 と 24.4 では想定通り(tar以外が解凍可能)なのを確認しましたが、どうにも 22.3 には mkdir 関数が無いんでしょうか、skk-get で mkdir が無いと言われます。
結構、色々と難しいようです。

**Comment by tkita** [comment]
mkdir $B$r$d$a$F!"(Bmake-directory $B$KJQ99$7$^$7$?!#(B

$B<j85$N(B emacs 22.3 $B$G!"%@%&%s%m!<%I$+$i2rE`$^$G(B
$B@5>o=*N;$9$k$3$H$r3NG'$7$^$7$?!#(B

**Comment by tkita** [comment]
mkdir をやめて、make-directory に変更しました。
手元の emacs 22.3 で、ダウンロードから解凍まで正常終了することを確認しました。

**Comment by tkita** [comment]
と思っていたら、delete-directory も。
emacs 22 は delete-directory に &optional RECURSIVE が無いのですね。

**Comment by yutopia** [comment]
gz解凍についての動作確認しました。

package.el を見てみたのですが、やっぱり tar-mode を使ってるみたいです。
package.el は tar ball からのインストールをしていたな、と思ったものですから。

**Comment by tkita** [comment]
tar-mode を参考にして tar-util.el を作ってみました。アーカイブからファイルを取り出すことができます。 
外部コマンドを使用しない pure elisp です。

**Comment by tkita** [comment]
いったん close します。
