### ISSUE TITLE
Installation error via MELPA

### ISSUE THREAD

**Issue by ktakashi** [skk-dev/ddskk#44]
I've faced 2 compilation error during installation of DDSKK via MELPA. 

1. `skk-lookup.el` requires `lookup` which isn't on MELPA.
2. `skk-develop.el` requires `tar-util` which is indeed in repository but seems not in MELPA files.

I've installed both packages manually and could install DDSKK however it might be more friendly if these are mentioned in `INSTALL.MELPA.md` files.

Installed version: ddskk-20160123.2212

**Comment by yutopia** [comment]
@ktakashi  the reason of both problems are no adjustment of ddskk package and MELPA recipe.
I will pull request to MELPA the new recipe, so wait a moment.

**Comment by yutopia** [comment]
MELPAのrecipeに tar-util.el が含まれていないことと、lookup-.el がなくてもskk-lookup.el をインストールしようとするのが原因です。
tar-util.el についてはrecipeに追加することにします。

lookup.el は開発元がskk-devとは違うので、githubに登録されることを待つわけにもいきませんから、とりあえず recipe から skk-lookup.el を はずす処置を取ろうと思います。
lookup.el を MELPA経由で入手する、もしくはddskk に取り込んでしまう、などの処置が取られたあとでこの箇所は再度議論しましょう。

**Comment by tkita** [comment]
対応ありがとうございます。

**Comment by tkita** [comment]
lookup.el を使わなくなって久しいですが、github に登録されているのですね。
https://github.com/lookup2/lookup2

eblook はどうなんだろう？

**Comment by yutopia** [comment]
とりあえず pull-req してきました。
反映はしばしお待ち下さい。

MELPAへの登録は原則配布元がするみたいなんで、正攻法ではlookup.el の開発者にお願いすることになるかと思います。

**Comment by tkita** [comment]
了解です。

**Comment by yutopia** [comment]
@ktakashi pull request for MELPA was merged, so the error will be corrected next package.
After you check the change, we will close this issue.

**Comment by ktakashi** [comment]
I've confirmed that there is no error during installation. Thanks :)

**Comment by yutopia** [comment]
thnx
