### ISSUE TITLE
Emacs22サポート

### ISSUE THREAD

**Issue by yutopia** [skk-dev/ddskk#46]
@tkita 
master の.travis.yml  から Emacs 22 のテストをはずしていいでしょうか？
make elc で止まるんでテストが failed になってしまうものですから。

**Comment by yutopia** [comment]
Emacs 22 のテストを切っておきました。
どちらにしろ make の段階でガードがかかるので問題は無いはず。

**Comment by tkita** [comment]
master 上からは、Emacs 22 に関連するコードをどんどん取っ払っていただいて構いません。
