### ISSUE TITLE
How to install NICOLA-DDSKK in NTEmacs

### ISSUE THREAD

**Issue by tkita** [skk-dev/ddskk#55]
何気に nicola ディレクトリを眺めていたところ、Makefile しかないため NTEmacs にインストールする手段が無いように思えました。
makeit.bat や Interactive Installer (SKK-MK) に相当するものが必要でしょうか。

**Comment by yutopia** [comment]
基本、 makeit.bat  は使いまわすこと前提ですので、make1.bat で NICOLA-DDSKK-MK をロードしてしかるべき関数を評価するようにすれば良いはずです。
make1.bat だけ作って置いておいてやれば動く、と思います。
ところでついでに気付いたのですが、README.w32.ja.org の中見を最近は全然検証していませんでした。

**Comment by tkita** [comment]
了解しました。make1.bat を作ろうと思います。
