### ISSUE TITLE
USキーボードにおける親指シフト環境の設定方法

### ISSUE THREAD

**Issue by smxshxishxad** [skk-dev/ddskk#64]
いつも開発、ありがとうございます。
USキーボードにて、skkの親指シフト環境を構築しようと思っておりますが、左親指シフトキーをMacの左commandキーに設定する方法がわからず、困っております。
ご存知の方がいらっしゃいましたら、ご教示いただけないでしょうか。

`.emacs.d/init.el`の設定内容
```
(require 'skk-setup)
(setq skk-use-kana-keyboard t)
(setq skk-kanagaki-keyboard-type 'nicola-dvorak)
(require 'skk-nicola-dvorak)
```

`.skk`の設定内容
```
(setq skk-use-kana-keyboard t)
(setq skk-kanagaki-keyboard-type 'nicola-dvorak)
```
以下、当方環境です。
OS: Mac OS X 10.13.2
Emacs: 25.3.1
入力方法: Dvorak-Qwerty
キーボード: Happy Hacking Keyboard（US配列）
尚、当方環境では左commandキーはsuperキーとして認識されているようです。

恐れ入りますが、アドバイスの程、よろしくお願いいたします。

**Comment by tkita** [comment]
Mac を使ったことがなく、親指シフトも使ったことがありませんので、まったくの妄想レベルです。
```
 (setq skk-nicola-lshift-keys '([super]))
```

当方、試す環境を持ち合わせていませんので、あしからず。

**Comment by smxshxishxad** [comment]
tkita様、ご親切にありがとうございました。
アドバイス頂いた方法では残念ながら実現できず、断念しました。
superキーをこの用途に用いるのはよくないのかもしれません。
次はxmodmapでキーマップを変更する方法を試してみて、だめなようでしたら、おとなしくキーボードを変えようと思います。

重ねて、お礼申し上げます。
