### ISSUE TITLE
Build an executable of ddskk/skk

### ISSUE THREAD

**Issue by loretoparisi** [skk-dev/ddskk#65]
Hello, I'm using kakasi as kanji to kana transliteration system. Specifically I have wrapped it in `node.js` for a simpler usage - see [here](https://github.com/loretoparisi/kakasi.js).
I would like to support ddskk / skk in the same way, but it's not clear to me if both are like packages extensions and the library can be built as standalone application.
I have successfully compiled `skktools-skktools-1_3_4` but I'm not sure what I have built and how to use it.

Thank you for your help in advance.

**Comment by tkita** [comment]
`skktools` is management tool for dictionary file merge/sort/convert.
Is your hope a kana to kanji with Javascript?

**Comment by tkita** [comment]
refer to `Anthy' https://ja.osdn.net/projects/anthy/releases/37536

BTW, API is no good? http://www.google.com/transliterate
see function skk-google-cgi-api-for-japanese-input().
```
(skk-google-cgi-api-for-japanese-input "かんじ")
=> ("感じ" "漢字" "幹事" "カンジ" "監事")
```

**Comment by loretoparisi** [comment]
@tkita thank you, in my case I would use offline. My aim is to invert romaji to kanji, that is why I was thinking to `skk`, so basically the opposite of kakasi, should it be possible right?

**Comment by tkita** [comment]
@loretoparisi さん、こんにちは。
あなたがやりたいことは大体理解しました。
ただしそれは、単純な「kakasi の逆」ではありません。

かな漢字からローマ字への変換は、ほぼ一意に求めることができます。
日本が好きです => にっぽん が すき です => nippon ga suki desu

ところが、ローマ字からかな漢字への変換は、必ずしも一意ではありません。
"ga" の一文字だけに着目しても「が」「画」「賀」「我」「蛾」と多くの候補があり、その文脈において最適な候補が何であるかを求めるにはアルゴリズムと創意工夫が必要です。
また、「nippongasukidesu」を「nippon ga suki desu」と意味のある区切りにする形態素解析も必要となります。

ddskk は、上記の「最適な候補の選択」と「形態素解析」を人間が行うと割り切ったかな漢字変換システムであり、極端に言えばあなたが望むものと最も遠いプログラムでしょう。

I hope someone will translate it into English.

**Comment by loretoparisi** [comment]
@tkita thank you so much for the clarification.  Assumed the google translated did it well, my reply below 👍 

I'm aware of the fact that the transliteration `romaji -> kanji` it is not unique, so you need some intelligence to get the best candidate among `k`. For Indian languages I'm using a `SHMM` model plus a Neural Network of the weights, then `Viterbi` is used for decoding to get the best of `K` candidates among the optimal ones.

Now I understand why there is a morphological analyzer  in `anthy-morphological-analyzer` and the `anthy-dic-tool `, thank you.

So we can say that `dkk` can be used as a intermediate step between kanji and romaji, but not as-it-is then.

What I'm working on right now it is a Tensorflow sequence 2 sequence neural network architecture that inverts romaji to kanji (a seq2seq machine learning task).

Thanks again for your help, closing then!

**Comment by tkita** [comment]
Sorry for my weird English.
I wish for the success of your project.
