### ISSUE TITLE
openlabから移転してはどうか

### ISSUE THREAD

**Issue by ohaguro123** [skk-dev/ddskk#66]
20181215現在openlabが落ちていてSKK公式にアクセスできません。
openlabは不安定なのか数ヶ月に一度は落ちているように思います。辞書やwiki各種文書も含めopenlabから完全移転してはどうでしょうか。一本化してしまえば、こちらとopenlabの間で辞書の同期をどうするのかという問題も考慮する必要はなくなります。

**Comment by tkita** [comment]
ご意見、ありがとうございます。
辞書については、配布ページ https://skk-dev.github.io/dict/ を用意しました。今後は cvs sync はやめようと思います。
wiki 各種文書については、もともと私の所管外であったため、私はどうしようもありません。

**Comment by tkita** [comment]
ご指摘ありがとうございます。
手始めに、 skk-develop.el 内の skk-get-download() 内の url を "https://github.com/skk-dev/dict/raw/gh-pages/" へ修正して手元で実行してみたところ、私の環境では
Package tls is obsolete!
Could not create connection to github.com:443
と怒られてしまいました。
私の環境が悪いのか、指している url が悪いのか、分かりますでしょうか？
なお、私は github に精通していません．
また、ブラウザ経由であれば上記urlでもファイルを取得できますので、（私の環境の）emacs の url-copy-file() が原因かもしれません。

**Comment by ayatakesi** [comment]
すいません、P.S.云々は勘違いでした...

**Comment by ayatakesi** [comment]
http://lists.gnu.org/archive/html/help-gnu-emacs/2019-02/msg00196.html
で紹介されているリンク先の
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")を試したところ、
(url-copy-file "https://github.com/skk-dev/dict/raw/gh-pages/SKK-JISYO.JIS2.gz" "~/test.gz")で取得できました。
私の環境は--without-gnutlsで構築したemacsなので外部PGとしてGnuTLSを呼んでると思いますが--with-gnutlsのemacsも同様に解決しないでしょうか？
(自分の環境では試せないです、すいません)

**Comment by tkita** [comment]
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3") を試してみましたが、エラーでした。
```
$ make get
emacs -batch -q -no-site-file -l tar-util.el -l skk-develop.el --eval='(skk-get "./dic")'
Contacting host: github.com:443
Opening TLS connection to ‘github.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 github.com’...
Package tls is obsolete!
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 github.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 github.com --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 github.com --protocols ssl3’...failed
Opening TLS connection to ‘github.com’...failed
Could not create connection to github.com:443
make: *** [Makefile:110: get] Error 255
```

ただし、私も --without-gnutls です。
```
system-configuration
"x86_64-pc-linux-gnu"

system-configuration-features
"XPM JPEG TIFF GIF PNG RSVG CAIRO DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZL\
IB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS XWIDGETS PDUMPER"

system-configuration-options
"--without-pop --with-sound=no --with-x-toolkit=gtk3 --with-cairo --without-gnutls --with-x --with-xwidgets 'CFLAGS=-Of\
ast -march=corei7 -mtune=corei7'"
```

**Comment by ayatakesi** [comment]
gnutlsを直接呼び出すとどーでしょうか？
自分の環境だと以下のように接続は問題なくできるようなんで、取得できたんだと思います
$ gnutls-cli --version
gnutls-cli 3.6.6
Copyright (C) 2000-2019 Free Software Foundation, and others, all rights reserved.
This is free software. It is licensed for use, modification and
redistribution under the terms of the GNU General Public License,
version 3 or later <http://gnu.org/licenses/gpl.html>


Please send bug reports to:  <bugs@gnutls.org>

$ gnutls-cli github.com
Processed 128 CA certificate(s).
Resolving 'github.com:443'...
Connecting to '192.30.255.112:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=github.com,O=GitHub\, Inc.,L=San Francisco,ST=California,C=US,serialNumber=5157550,jurisdictionOfIncorporationStateOrProvinceName=Delaware,jurisdictionOfIncorporationCountryName=US,businessCategory=Private Organization', issuer `CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0a0630427f5bbced6957396593b6451f, RSA key 2048 bits, signed using RSA-SHA256, activated `2018-05-08 00:00:00 UTC', expires `2020-06-03 12:00:00 UTC', pin-sha256="o5oa5F4LbZEfeZ0kXDgmaU2K3sIPYtbQpT3EQLJZquM="
	Public Key ID:
		sha1:b5fa0cf2e698ddd62f04e4404faa11801704f7c8
		sha256:a39a1ae45e0b6d911f799d245c3826694d8adec20f62d6d0a53dc440b259aae3
	Public Key PIN:
		pin-sha256:o5oa5F4LbZEfeZ0kXDgmaU2K3sIPYtbQpT3EQLJZquM=

- Certificate[1] info:
 - subject `CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US', issuer `CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0c79a944b08c11952092615fe26b1d83, RSA key 2048 bits, signed using RSA-SHA256, activated `2013-10-22 12:00:00 UTC', expires `2028-10-22 12:00:00 UTC', pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="
- Status: The certificate is trusted. 
- Description: (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-128-GCM)
- Options:
- Handshake was completed

- Simple Client Mode:

- Peer has closed the GnuTLS connection

**Comment by tats** [comment]
@tkita, https://github.com/skk-dev/ddskk/issues/66#issuecomment-463187380:
> Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 github.com’...
> Package tls is obsolete!

gnutls.elでなくtls.elを使っているようなので、`gnutls-algorithm-priority`
は効かないのではないでしょうか。失敗の原因はわかりませんが、tls.elで
`-VERS-TLS1.3`を指定したいなら`tls-program`で指定してはどうでしょうか。

```
(setq tls-program '("gnutls-cli --x509cafile %t --priority SECURE128:-VERS-SSL3.0:-VERS-TLS1.3 -p %p %h"))
```

**Comment by tats** [comment]
@ayatakesi, https://github.com/skk-dev/ddskk/issues/66#issuecomment-463033876:
> http://lists.gnu.org/archive/html/help-gnu-emacs/2019-02/msg00196.html
> で紹介されているリンク先の
> (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")を試したところ、
> (url-copy-file "https://github.com/skk-dev/dict/raw/gh-pages/SKK-JISYO.JIS2.gz" "~/test.gz")で取得できました。

そのリンク先の返信を見ると、Emacs側の問題で修正済みとのことです。
cf. http://lists.gnu.org/archive/html/help-gnu-emacs/2019-02/msg00204.html

手元では、Emacs 26.1や去年12月時点の27.0.50だと`url-copy-file`に失敗
(`-VERS-TLS1.3`を加えると成功)しますが、2019/2/12時点の27.0.50では
`-VERS-TLS1.3`なしでもうまくいきます。

**Comment by ayatakesi** [comment]
むう...
そーするとobsolete云々は
https://github.com/emacs-mirror/emacs/blob/master/lisp/obsolete/tls.el
に由来するものかも(obsoleteになるのは27.1からの筈なんですが

**Comment by ayatakesi** [comment]
家のemacs-26.1だとtls.elは/obsoleteに居らず/netに居り

```emacs-lisp
(require 'gnutls)
```

してます

**Comment by tkita** [comment]
返信遅れました。
私が試した emacs は 27 です。
```
(version)
"GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.12)
 of 2019-02-10"
```
```
$ ls net/tls*
ls: cannot access 'net/tls*': No such file or directory
$ ls obsolete/tls*
obsolete/tls.el  obsolete/tls.elc
```

**Comment by tats** [comment]
@tkita, https://github.com/skk-dev/ddskk/issues/66#issuecomment-460601860:
> skk-develop.el 内の skk-get-download() 内の url を "https://github.com/skk-dev/dict/raw/gh-pages/" へ修正して手元で実行してみたところ、

github.ioだとTLS 1.3は使われないようですので、urlを
"https://skk-dev.github.io/dict/"
にしてはどうでしょうか。

**Comment by ayatakesi** [comment]
skk-develop.elのリンク先を
`https://skk-dev.github.io/dict/`
にして`skk-get`を実行したら無事取得できました。
ありがとうございました

**Comment by tkita** [comment]
@tats さま、 @ayatakesi さま、いろいろありがとうございます。
私の手元の GNU Emacs 26.1 / windows で make get が動きましたので、先ほど push しておきました。

ちなみに、GNU Emacs 27.0.50 / fedora 28 だと URL 変更後もやはりエラーですが、私の環境が原因かもしれませんので無視してください。

```
$ make get
emacs -batch -q -no-site-file -l tar-util.el -l skk-develop.el --eval='(skk-get "./dic")'
Contacting host: skk-dev.github.io:443
Opening TLS connection to ‘skk-dev.github.io’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 skk-dev.github.io’...
Package tls is obsolete!
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 skk-dev.github.io’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 skk-dev.github.io --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 skk-dev.github.io --protocols ssl3’...failed
Opening TLS connection to ‘skk-dev.github.io’...failed
Could not create connection to skk-dev.github.io:443
```

**Comment by tkita** [comment]
GNU Emacs 27.0.50 / fedora 28 でも
```
# dnf install gnutls*
```
を実行したら make get できました。

**Comment by tkita** [comment]
melpa を使っていない私が言う立場じゃないですけれど、
辞書もパッケージ化できればお手軽に更新できますでしょうか？

**Comment by tats** [comment]
> 辞書については、配布ページ https://skk-dev.github.io/dict/ を用意しました。今後は cvs sync はやめようと思います。

GitHubへ誘導するようOpenLabのサイトを更新してはどうでしょうか。

  - http://openlab.jp/skk/dic.html
  - http://openlab.jp/skk/dic-ja.html

**Comment by tkita** [comment]
OpenLab のサイトを更新してみました。
特に英語の添削をお願いできるでしょうか。

**Comment by tats** [comment]
ありがとうございます。
「布ファイル」は「配布ファイル」でしょうか。

**Comment by tkita** [comment]
ご指摘のとおり「配布ファイル」であり、修正しました。
（まったく気づいてませんでした）

**Comment by tkita** [comment]
@ohaguro123 さんによるてご提案「辞書やwiki各種文書も含めopenlabから完全移転してはどうか」について、そのすべてを解決した訳ではありませんが、辞書の移転は完了できたと思われるため、いったんクローズさせていただきます。
