### ISSUE TITLE
set-process-coding-system vs. set-buffer-process-coding-system

### ISSUE THREAD

**Issue by tetsuotsukamoto** [skk-dev/ddskk#72]
Dear all,

As the former function takes BUFFER as the 1st arg while the latter assumes the current buffer, so I think the following change will be necessary to avoid the processp error.

Kind regards,

Tetsuo Tsukamoto

--- skk-annotation.el.orig	2019-04-23 09:10:01.000000000 +0900
+++ skk-annotation.el	2019-04-23 09:14:26.000000000 +0900
@@ -1046,7 +1046,8 @@
         ;; Jan 15 2018, lisp/international/mule.el
         ;; *  (set-buffer-process-coding-system): Mark as interactive-only.
         ;; *  in Lisp code use 'set-process-coding-system' instead.
-	(set-process-coding-system 'utf-8-unix 'utf-8-unix)
+	(set-process-coding-system (get-buffer-process (current-buffer))
+				   'utf-8-unix 'utf-8-unix)
 
 	(skkannot-py-send-command "import DictionaryServices")
 	(cond ((and wait (skkannot-sit-for 1.0))

**Comment by tkita** [comment]
ご指摘、ありがとうございます。
