### ISSUE TITLE
ソースのUTF-8化

### ISSUE THREAD

**Issue by conao3** [skk-dev/ddskk#73]
#19 と #20 で.texiファイルについてUTF-8化が行われたように思います。しかし他のElispなどはGitHubで表示できず、moccurで検索した際にもうまく表示できず困っています。（適切な設定があるのだと思いますが。。。）
文字コードに詳しくないのですが、 `iso-2022-jp` から `UTF-8` に変換した場合、どのような問題が起こると考えられますでしょうか？

**Comment by tkita** [comment]
jis x 0208 による文字の並び順を前提としたコーディングの個所は、Unicode 化に伴って誤動作する可能性があります。
関数 skk-what-char-type を見ていただければイメージがつかめるかと。

**Comment by conao3** [comment]
分かりました。やはり文字コード関連は難しいですね。。
