### ISSUE TITLE
README.mdについて

### ISSUE THREAD

**Issue by ohaguro123** [skk-dev/ddskk#75]
README.mdの最下部
If you want to commit something to skk-dev/ddskk repository, please join the ddskk-committers team. 
のddskk-committers teamのリンク先が404になっています。リンク修正をお願いします。

**Comment by tats** [comment]
> **If you want to commit something to skk-dev/ddskk repository, please join the [ddskk-committers team](https://github.com/orgs/skk-dev/teams/ddskk-committers)**.

secret設定になっており、該当ページはメンバー以外から見えないのですね。

実際のメンバーへの参加は、プルリクエスト等での活動実績により勧誘される形
でしょうから、この文自体を削除してしまってもよいのかもしれません。

**Comment by tats** [comment]
Fixed by https://github.com/skk-dev/ddskk/pull/154
