### ISSUE TITLE
How to disable prompt when package-install ddskk to whether viper on/off

### ISSUE THREAD

**Issue by conao3** [skk-dev/ddskk#76]
ddskkをpackage-installした際にviperを有効にするかどうか聞いてきま
すが、パッケージインストール時に入力を要求するパッケージはあまり
ないように思います。.emacs.dを最初に使う時にある変数にリストされ
ているパッケージをインストールするようにしているのですが、ddskkの
要求するプロンプトによってインストールが途中で止まってしまいます。

viperを有効にする人はinit.elに対応する設定を書けばいいだけで、全
ての人にプロンプトを出す必要はないように思うのですが、このプロン
プトはどのような観点から現在設定されているのでしょうか。。？

**Comment by tkita** [comment]
いま、M-x package-install を試してみたところ、viper どころか何らプロンプトは表示されずに正常終了しました。M-x version は次のとおり。
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29 です。

**Comment by conao3** [comment]
こちらではこのようなプロンプトが表示されます。
プロンプトに応答するまでinit.elの評価がブロックされるため、このプロンプト表示を止めたいと思っています。

![capture_2019-12-10_21-30-11](https://user-images.githubusercontent.com/4703128/70528950-bee3d980-1b92-11ea-8053-1c43a94952b6.png)

ちなみに下記のinit.elを `emacs -q -l {{file}}` で読み込んで再現することを確認しました。

```emacs-lisp
;; ~/.debug.emacs.d/ox-latex-subfigure/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "prepare leaf"
  (prog1 "package"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize))

  (prog1 "leaf"
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))



(leaf skk
  :ensure ddskk
  :require t skk-study
  :bind (("C-\\" . skk-mode))
  :custom ((default-input-method . "japanese-skk")))
```

**Comment by tkita** [comment]
PR 頂戴いただければ取り込みます。
