### ISSUE TITLE
End of xemacs support

### ISSUE THREAD

**Issue by tkita** [skk-dev/ddskk#87]
16.3 をもって xemacs のサポートを終了することとし、次期リリースに向けた master ブランチでは xemacs 関連コードを削除しようと思います。
ご意見ございましたら寄せていただければと思います。

**Comment by tats** [comment]
すでにcl-libによってXEmacs非対応になっているようですが、とくに異存はありません。

**Comment by tkita** [comment]
おはずかしい。xemacs で make 試験すら行わずに commit している実態が露呈してしまいました。
ここ数年このような状況であるにも関わらず xemacs 関連の指摘が寄せられたこともありませんでしたので、いっそのことサポート終了を宣言すべきかなと思いまして。
